Repository Esri/calcite-react, pull requests merged in 2019-10, with the labels that each got.

#296 FormHelperText height => min-height
  src/Form/Form-styled.js
Labels: bug

#293 Add pointer-events none to disabled inputs
  src/utils/commonElements.js
Labels: bug

#288 Add `theme` to defaultProps for each styled-component
  CONTRIBUTING.md
  doczrc.js
  src/Accordion/Accordion-styled.js
  src/Alert/Alert-styled.js
  src/ArcgisAccount/ArcgisAccount-styled.js
  src/ArcgisItemCard/ArcgisItemCard-styled.js
  src/ArcgisShare/ArcgisShare-styled.js
  src/Avatar/Avatar-styled.js
  src/Breadcrumbs/Breadcrumbs-styled.js
  src/Button/Button-styled.js
  src/Card/Card-styled.js
  src/Checkbox/Checkbox-styled.js
  src/ComboButton/ComboButton-styled.js
  src/CopyToClipboard/CopyToClipboard-styled.js
  src/DatePicker/DatePicker-styled.js
  src/Drawer/Drawer-styled.js
  src/Elements/Elements-styled.js
  src/FileUploader/FileUploader-styled.js
  src/Form/Form-styled.js
  src/Label/Label-styled.js
  src/List/List-styled.js
  src/Loader/Loader-styled.js
  src/Menu/Menu-styled.js
  src/Modal/Modal-styled.js
  src/MultiSelect/MultiSelect-styled.js
  src/Panel/Panel-styled.js
  src/Popover/Popover-styled.js
  src/Radio/Radio-styled.js
  src/Search/Search-styled.js
  src/Search/doc/StyledSearch.js
  src/Select/Select-styled.js
  src/SideNav/SideNav-styled.js
  src/Slider/Slider-styled.js
  src/Stepper/Stepper-styled.js
  src/SubNav/SubNav-styled.js
  src/Switch/Switch-styled.js
  src/Table/Table-styled.js
  src/Tabs/Tab-styled.js
  src/TextField/TextField-styled.js
  src/Toaster/Toaster-styled.js
  src/Tooltip/Tooltip-styled.js
  src/TopNav/TopNav-styled.js
  src/utils/commonElements.js
Labels: enhancement

#301 Add Tooltip enterDelay to CalciteTheme
  docz/GuideExample.js
  src/CalciteThemeProvider/CalciteTheme.js
  src/Tooltip/Tooltip.js
Labels: enhancement

#302 Update popper elements on content resize
  package-lock.json
  package.json
  src/MultiSelect/MultiSelect-styled.js
  src/MultiSelect/MultiSelect.js
  src/MultiSelect/MultiSelectMenu.js
  src/Popover/Popover-styled.js
  src/Popover/Popover.js
  src/Popover/PopoverPopper.js
  src/Popover/doc/Popover.mdx
  src/Search/Search.js
  src/Search/SearchMenu.js
  src/Select/Select-styled.js
  src/Select/Select.js
  src/Select/SelectMenu.js
  src/Tooltip/Tooltip-styled.js
  src/Tooltip/Tooltip.js
  src/Tooltip/TooltipPopper.js
Labels: bug, enhancement
