Repository Esri/calcite-react, pull requests merged in 2021-03, with the labels that each got.

#445 Update calcite-colors references to 6.0.0
  docz/DoczCalciteTheme.js
  package-lock.json
  package.json
  src/Avatar/doc/Avatar.mdx
  src/CalciteThemeProvider/CalciteTheme.js
  src/Loader/doc/Loader.mdx
  src/Slider/Slider-styled.js
  src/Switch/Switch-styled.js
Labels: task

#458 Export `toast` object imported from `react-toastify` to give users access to increased `toast` methods.
  src/Toaster/Toaster.js
  src/Toaster/doc/Toaster.mdx
  src/Toaster/index.js
Labels: enhancement, feature request

#459 Fix brand color usage, add new theme vars
  package-lock.json
  src/CalciteThemeProvider/CalciteTheme.js
  src/Slider/Slider-styled.js
Labels: bug, enhancement
